version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: occ-frontend
    restart: unless-stopped
    networks:
      - my-network

  backend:
    build: ./occportal
    ports:
      - "5000:5000"
    container_name: occ-backend
    restart: unless-stopped
    environment:
      - PORT=5000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
