spring:
  application:
    name: occapi
  datasource:
    url: jdbc:postgresql://185.250.44.151:5432/mydb
    username: admin
    password: secret
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 5000
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger
