spring:
  application:
    name: occapi
#    datasource:
#      url: jdbc:h2:file:./data/db
#      driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://185.250.44.151:5432/mydb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 5000
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger
